import './globals.css'
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata = {
  title: 'My Next.js Website',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body>
        <Header />
        <main style={{ minHeight: '80vh', padding: '20px' }}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
